import json, os, subprocess

with open('/tmp/runtime_findings.json') as f:
    data = json.load(f)

repo = os.environ.get('GITHUB_REPO', 'sautalwar/cushman-property-api')
icons = {'critical': '🔴', 'high': '🟠', 'medium': '🟡', 'low': '🔵'}

for finding in data.get('findings', []):
    vuln_id = finding['id']
    sev     = finding['severity']
    icon    = icons.get(sev, '⚠️')

    # Check if an open issue for this vuln already exists
    existing = subprocess.run(
        ['gh', 'issue', 'list', '--repo', repo,
         '--label', f'vuln:{vuln_id}', '--state', 'open', '--json', 'number'],
        capture_output=True, text=True
    )
    if existing.stdout.strip() not in ('', '[]', 'null'):
        print(f"Issue already open for {vuln_id} — skipping")
        continue

    body = f"""## {icon} Runtime Security Finding: `{vuln_id}`

**Severity:** `{sev.upper()}`
**OWASP Category:** {finding['rule']}
**Affected file:** `{finding['file']}` (line {finding['line']})

---

### 🔬 What was detected

{finding['message']}

---

### 🤖 AI-Recommended Fix (Copilot)

```typescript
// {finding['fix']}
```

---

### ✅ How to respond

This issue was created automatically by the Security Posture workflow.
Choose one of the following actions:

| Action | How | Result |
|--------|-----|--------|
| **Apply the fix** | Add label `apply-fix` | Copilot opens a PR with the patch |
| **Accept the risk** | Add label `risk-accepted` | Issue closed, finding suppressed |
| **Investigate** | Leave open | Stays in security backlog |

---
*Auto-generated by Security Posture Dashboard · Run [{os.environ.get('GITHUB_RUN_ID','')}](https://github.com/{repo}/actions/runs/{os.environ.get('GITHUB_RUN_ID','')})*
"""

    result = subprocess.run(
        ['gh', 'issue', 'create', '--repo', repo,
         '--title', f"{icon} Security Finding: {vuln_id} — {finding['rule'][:60]}",
         '--body', body,
         '--label', 'security,ai-recommendation,' + f'vuln:{vuln_id},{sev}'],
        capture_output=True, text=True
    )
    if result.returncode == 0:
        print(f"Created issue for {vuln_id}: {result.stdout.strip()}")
    else:
        print(f"Could not create issue for {vuln_id}: {result.stderr[:200]}")
